layout: {qmk_keyboard: adv360}
layers:
  qwerty:
  - '='
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - {t: keypad, h: toggle}
  - mod
  - '6'
  - '7'
  - '8'
  - '9'
  - '0'
  - '-'
  - TAB
  - Q
  - W
  - E
  - R
  - T
  - {t: querty_prog, h: toggle}
  - PSCRN
  - Y
  - U
  - I
  - O
  - P
  - \
  - ESC
  - {t: A, h: LGUI}
  - {t: S, h: LALT}
  - {t: D, h: LCTRL}
  - {t: F, h: LSHFT}
  - {t: G, h: keypad}
  - {t: dvorak_prog, h: toggle}
  - LCTRL
  - LALT
  - LGUI
  - RCTRL
  - INS
  - H
  - {t: J, h: RSHFT}
  - {t: K, h: RCTRL}
  - {t: L, h: RALT}
  - {t: ;, h: RGUI}
  - ''''
  - LSHFT
  - Z
  - X
  - C
  - V
  - B
  - HOME
  - PG UP
  - N
  - M
  - ','
  - .
  - /
  - RSHFT
  - fn
  - '`'
  - CAPS
  - LEFT
  - RIGHT
  - BSPC
  - DEL
  - END
  - PG DN
  - ENTER
  - SPACE
  - UP
  - DOWN
  - '['
  - ']'
  - fn
  querty_prog:
  - {t: '|', s: '`'}
  - {t: +, s: '1'}
  - {t: '[', s: '2'}
  - {t: '{', s: '3'}
  - {t: (, s: '4'}
  - {t: '&', s: '5'}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: '=', s: '6'}
  - {t: ), s: '7'}
  - {t: '}', s: '8'}
  - {t: ']', s: '9'}
  - {t: '*', s: '0'}
  - {t: '!', s: '%'}
  - {t: ▽, type: trans}
  - Q
  - W
  - E
  - R
  - T
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - Y
  - U
  - I
  - O
  - P
  - {t: \, s: '#'}
  - {t: ▽, type: trans}
  - {t: A, h: LGUI}
  - {t: S, h: LALT}
  - {t: D, h: LCTRL}
  - {t: F, h: LSHFT}
  - {t: G, h: keypad}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - H
  - {t: J, h: RSHFT}
  - {t: K, h: RCTRL}
  - {t: L, h: RALT}
  - {t: ;, h: RGUI}
  - '-'
  - {t: ▽, type: trans}
  - Z
  - X
  - C
  - V
  - B
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - N
  - M
  - ','
  - .
  - /
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: $, s: '~'}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - ''''
  - {t: '@', s: ^}
  - {t: ▽, type: trans}
  dvorak_prog:
  - {t: '|', s: '`'}
  - {t: +, s: '1'}
  - {t: '[', s: '2'}
  - {t: '{', s: '3'}
  - {t: (, s: '4'}
  - {t: '&', s: '5'}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: '=', s: '6'}
  - {t: ), s: '7'}
  - {t: '}', s: '8'}
  - {t: ']', s: '9'}
  - {t: '*', s: '0'}
  - {t: '!', s: '%'}
  - {t: ▽, type: trans}
  - ;
  - ','
  - .
  - P
  - Y
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - F
  - G
  - C
  - R
  - L
  - {t: \, s: '#'}
  - {t: ▽, type: trans}
  - {t: A, h: LGUI}
  - {t: O, h: LALT}
  - {t: E, h: LCTRL}
  - {t: U, h: LSHFT}
  - {t: I, h: keypad}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - D
  - {t: H, h: RSHFT}
  - {t: T, h: RCTRL}
  - {t: N, h: RALT}
  - {t: S, h: RGUI}
  - '-'
  - {t: ▽, type: trans}
  - ''''
  - Q
  - J
  - K
  - X
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - B
  - M
  - W
  - V
  - Z
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: $, s: '~'}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - /
  - {t: '@', s: ^}
  - {t: ▽, type: trans}
  dvorak:
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - ;
  - ','
  - .
  - P
  - Y
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - F
  - G
  - C
  - R
  - L
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - A
  - O
  - E
  - U
  - I
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - D
  - H
  - T
  - N
  - S
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - ''''
  - Q
  - J
  - K
  - X
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - B
  - M
  - W
  - V
  - Z
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  keypad:
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - KP NUM
  - KP EQUAL
  - KP DIVIDE
  - KP MULTIPLY
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - KP 7
  - KP 8
  - KP 9
  - KP MINUS
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - KP 4
  - KP 5
  - KP 6
  - KP PLUS
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - KP 1
  - KP 2
  - KP 3
  - KP ENTER
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - KP 0
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - KP DOT
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  fn:
  - F1
  - F2
  - F3
  - F4
  - F5
  - F6
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - F7
  - F8
  - F9
  - F10
  - F11
  - F12
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: qwerty, h: toggle}
  - ''
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: dvorak, h: toggle}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - ''
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - APP
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  mod:
  - ''
  - {t: BT, h: '0'}
  - {t: BT, h: '1'}
  - {t: BT, h: '2'}
  - {t: BT, h: '3'}
  - {t: BT, h: '4'}
  - ''
  - {type: held}
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - '&bootloader'
  - '&bootloader'
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - BT CLR
  - ''
  - RGB MEFS CMD 5
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - '&bl BL_TOG'
  - RGB TOG
  - '&bl BL_INC'
  - '&bl BL_DEC'
  - ''
  - ''
  - ''
